# Generated by Django 3.0.3 on 2020-02-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddProduct',
            new_name='AddProductModel',
        ),
    ]
