# Generated by Django 3.0.3 on 2020-02-09 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200209_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproductmodel',
            name='product_img',
        ),
    ]
