# Generated by Django 3.0.3 on 2020-02-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_addproductmodel_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCartModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_Id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=500)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
